### ISSUE TITLE
Azure AD Authorization

### ISSUE THREAD

**Issue by Ryan2065** [Eph-It/Automation#6]
Need Azure AD authorization working.

Needs a user table to handle Azure AD users that validates unique users based on tenant id and user guid.

Note - I already have it working (to authorize a user and get their claim information), just need the supporting code behind working in the Register method to add them to the DB and validate if they have permission.

**Comment by fredbainbridge** [comment]
The tenant id needs to be known ahead of time and then a graph calls needs to be made to authenticate?  Is that how this will work?  My lab device is not AD joined only Azure AD, so I am inclined to get this functional so we can tie the bigger ecosystem into the service.

**Comment by Ryan2065** [comment]
So we don't need to necessarily know the tenant id. I have a publish Azure branch that has initial functionality. It doesn't work yet, but if you turn on anonymous authentication it'll prompt for Azure AD credentials. Then if you debug in the Authentication middleware where it has an "if WindowsAuthentication" but no else, you'll see there's a user object who is listed as authenticated and the user, tenant id, etc are all there. 

So we can just handle it like standard windows auth where the tenant id is the domain and there's a guid passed for unique user id (instead of SID). It also should have group information of the user as I made the application request that.
